#!/usr/bin/env bash
set -euo pipefail

# cmux post-create hook: generate a per-workspace Docker Compose override that
# remaps every host-published port onto this workspace's CMUX_PORT block, so
# parallel cmux workspaces never collide on host ports. Runs with cwd = the new
# worktree root.

: "${CMUX_PORT:?CMUX_PORT must be set by cmux before running this hook}"

slug="${CMUX_FEATURE_SLUG:-cmux}"

# Contiguous port block starting at CMUX_PORT.
webui_port=$CMUX_PORT
temporal_grpc_port=$((CMUX_PORT + 1))
temporal_ui_port=$((CMUX_PORT + 2))
api_port=$((CMUX_PORT + 3))
redis_port=$((CMUX_PORT + 4))

cat > compose.override.yml <<EOF
# Generated by .cmux/post-create.sh for this cmux workspace — DO NOT edit or commit.
# Remaps host-published ports onto this workspace's CMUX_PORT block (base ${CMUX_PORT})
# so parallel cmux workspaces never collide. Auto-loaded by \`docker compose\`.
services:
  temporal:
    # container_name is hardcoded in compose.yml; suffix it so workspaces don't clash.
    # Service DNS still resolves via the \`temporal\` service name, so internal
    # addresses (temporal:7233) are unaffected.
    container_name: temporal-${slug}
    ports: !override
      - "${temporal_grpc_port}:7233"
      - "${temporal_ui_port}:8233"

  redis:
    container_name: redis-${slug}
    ports: !override
      - "${redis_port}:6379"

  api:
    ports: !override
      - "${api_port}:8000"

  frontend:
    environment:
      # Browser-evaluated, so it must point at THIS workspace's API host port.
      NUXT_PUBLIC_API_BASE: "http://localhost:${api_port}"
    ports: !override
      - "${webui_port}:3000"
EOF

cat <<EOF
cmux workspace "${slug}" compose ports (base ${CMUX_PORT}):
  Web UI         http://localhost:${webui_port}
  Temporal UI    http://localhost:${temporal_ui_port}
  Temporal gRPC  localhost:${temporal_grpc_port}
  API            http://localhost:${api_port}
  Redis          localhost:${redis_port}
EOF
