.DEFAULT_GOAL := help

# Canonical environment for host-side targets. Optional: a missing .env is fine.
ifneq (,$(wildcard .env))
include .env
export
endif

# compose.override.yml (auto-merged by docker compose) may remap the published
# host ports so parallel workspaces never collide — it is generated per workspace
# by `make worktree-ports` (Casper) or .cmux/post-create.sh (cmux). When present,
# read the actual published ports straight from it so the banner and the host-side
# `make dev` flow can never diverge from what docker binds. Otherwise fall back to
# the conventional defaults.
ifneq (,$(wildcard compose.override.yml))
FRONTEND_PORT      := $(shell sed -nE 's/.*"([0-9]+):3000".*/\1/p' compose.override.yml | head -n1)
TEMPORAL_GRPC_PORT := $(shell sed -nE 's/.*"([0-9]+):7233".*/\1/p' compose.override.yml | head -n1)
TEMPORAL_UI_PORT   := $(shell sed -nE 's/.*"([0-9]+):8233".*/\1/p' compose.override.yml | head -n1)
API_PORT           := $(shell sed -nE 's/.*"([0-9]+):8000".*/\1/p' compose.override.yml | head -n1)
# Point the host-side dev flow (uv worker/api, Nuxt) at this workspace's ports.
TEMPORAL_ADDRESS     ?= localhost:$(TEMPORAL_GRPC_PORT)
NUXT_PUBLIC_API_BASE ?= http://localhost:$(API_PORT)
NUXT_PORT            ?= $(FRONTEND_PORT)
export TEMPORAL_ADDRESS API_PORT NUXT_PUBLIC_API_BASE NUXT_PORT
else
FRONTEND_PORT    ?= 3000
API_PORT         ?= 8000
TEMPORAL_UI_PORT ?= 8233
endif

# Banner listing where to reach the running components.
define show_urls
	@echo ""
	@echo "The stack is up. Open:"
	@echo "  Frontend           http://localhost:$(FRONTEND_PORT)"
	@echo "  API                http://localhost:$(API_PORT)"
	@echo "  Temporal dashboard http://localhost:$(TEMPORAL_UI_PORT)"
endef

##@ App (host, hot reload)

.PHONY: install
install: ## Install backend and frontend dependencies
	$(MAKE) -C backend install
	$(MAKE) -C frontend install

.PHONY: dev
dev: infra-up ## Run the frontend and backend in dev mode with hot-reload
	@cd frontend && pnpm install --prefer-offline --silent
	$(show_urls)
	$(MAKE) -j3 worker-dev api-dev ui

.PHONY: worker
worker: ## Run the Temporal worker
	$(MAKE) -C backend worker

.PHONY: api
api: ## Run the HTTP API
	$(MAKE) -C backend api

.PHONY: worker-dev
worker-dev: ## Run the Temporal worker with auto-reload
	$(MAKE) -C backend worker-dev

.PHONY: api-dev
api-dev: ## Run the HTTP API with auto-reload
	$(MAKE) -C backend api-dev

.PHONY: ui
ui: ## Run the Nuxt dev server
	$(MAKE) -C frontend dev

##@ Infra

.PHONY: infra-up
infra-up: ## Start Temporal dev server + Redis (Temporal gRPC :7233, UI :8233, Redis :6379)
	docker compose up -d --wait temporal redis

.PHONY: infra-down
infra-down: ## Stop Temporal dev server + Redis
	docker compose stop temporal redis

.PHONY: infra-logs
infra-logs: ## Follow Temporal dev server + Redis logs
	docker compose logs -f temporal redis

##@ Stack (Docker)

.PHONY: app-up
app-up: ## Bring up the full stack in Docker (Temporal + Redis + worker + API + frontend)
	docker compose up -d
	$(show_urls)

.PHONY: app-down
app-down: ## Tear down the whole Docker stack
	docker compose down

.PHONY: app-logs
app-logs: ## Follow logs from every stack container
	docker compose logs -f

##@ Worktree

.PHONY: worktree-ports
worktree-ports: ## Remap host ports off CASPER_PORT so parallel worktrees don't collide
	@if [ -z "$$CASPER_PORT" ]; then \
		echo "CASPER_PORT is not set — skipping port remap."; \
	else \
		slug=$$(printf '%s' "$${CASPER_WORKSPACE_ID:-casper}" | tr 'A-Z' 'a-z' | cut -c1-8); \
		grpc=$$((CASPER_PORT + 1)); ui=$$((CASPER_PORT + 2)); \
		api=$$((CASPER_PORT + 3)); redis=$$((CASPER_PORT + 4)); \
		printf '%s\n' \
			"# Generated by 'make worktree-ports' for this Casper workspace — DO NOT edit or commit." \
			"# Remaps host-published ports onto this workspace's CASPER_PORT block (base $$CASPER_PORT)" \
			"# so parallel Casper workspaces never collide. Auto-loaded by docker compose." \
			"services:" \
			"  temporal:" \
			"    container_name: temporal-$$slug" \
			"    ports: !override" \
			"      - \"$$grpc:7233\"" \
			"      - \"$$ui:8233\"" \
			"" \
			"  redis:" \
			"    container_name: redis-$$slug" \
			"    ports: !override" \
			"      - \"$$redis:6379\"" \
			"" \
			"  api:" \
			"    ports: !override" \
			"      - \"$$api:8000\"" \
			"" \
			"  frontend:" \
			"    environment:" \
			"      NUXT_PUBLIC_API_BASE: \"http://localhost:$$api\"" \
			"    ports: !override" \
			"      - \"$$CASPER_PORT:3000\"" \
			> compose.override.yml; \
		echo "Casper workspace compose ports (base $$CASPER_PORT):"; \
		echo "  Frontend       http://localhost:$$CASPER_PORT"; \
		echo "  Temporal gRPC  localhost:$$grpc"; \
		echo "  Temporal UI    http://localhost:$$ui"; \
		echo "  API            http://localhost:$$api"; \
		echo "  Redis          localhost:$$redis"; \
	fi

##@ Quality

.PHONY: lint
lint: ## Lint backend and frontend
	$(MAKE) -C backend lint
	$(MAKE) -C frontend lint

.PHONY: format
format: ## Format backend and frontend
	$(MAKE) -C backend format
	$(MAKE) -C frontend format

##@ Helpers

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z0-9_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(firstword $(MAKEFILE_LIST))
